services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8080:8080'
    networks:
      - dchat

networks:
  dchat:
    driver: bridge
    